

custom:
  datasource:
    enable: true
    properties:
    -
        name: default
        url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 3401231996
        driver-class-name: com.mysql.cj.jdbc.Driver